# GLOBAL SITE SETTINGS

# General
seo_title: ""
title: "Baggio Legal"
company: "Baggio Legal"
description: "..."

# Contact Info
email_1:
phone_1: +61 8 8132 5000
phone_2: +61 8 8363 1633
skype: andrewrbaggio

fax: (05) 555 555
address: "Dequette Chambers<br> 1 Dequetteville Terrace<br> Kent Town SA 5067"

# Social Networks
facebook: ""
vimeo: ""
twitter: ""
instagram: ""

# Google Map
google_map: "https://www.google.com.au/maps/place/Baggiolegal/@-34.919799,138.615468,15z/data=!4m2!3m1!1s0x0:0xa164f0a946eb47de?sa=X&amp;ved=0CGwQ_BIwCmoVChMI79zBxPWIxgIVx3y8Ch1aAgCi"

# Google Analytics
google_analytics: "UA-XXXXXXXX-X"